apiVersion: v2
appVersion: 2.5.8
description: An Application dashboard and launcher
name: heimdall
version: 1.0.4
kubeVersion: ">=1.16.0-0"
keywords:
  - heimdall
  - dashboard
home: https://github.com/egeback/helm-charts/tree/main/charts/heimdall
icon: https://i.imgur.com/mM4tcO5.png
sources:
  - https://hub.docker.com/r/linuxserver/heimdall/
  - https://github.com/linuxserver/heimdall
maintainers:
  - name: egeback
    email: marky@egeback.se
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial version
    - kind: added
      description: Update README.md
