#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#
controllers:
  main:
    containers:
      app:
        image:
          # -- image repository
          repository: linuxserver/heimdall
          # -- image tag
          tag: "{{ .Chart.AppVersion }}"
          # -- image pull policy
          pullPolicy: IfNotPresent

        # -- environment variables. See more environment variables in the [heimdall documentation](https://github.com/linuxserver/docker-heimdall#parameters).
        # @default -- See below
        env:
          # -- Set the container timezone
          TZ: UTC
          # -- Set the container user id
          PUID: "1000"
          # -- Set the container group id
          PGID: "1000"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    controller: main
    ports:
      http:
        port: 80

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false
    hosts:
    - host: heimdall.example.com
      paths:
        - path: /
          pathType: Prefix
          service:
            identifier: main
            port: http

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: false
