remote: origin
target-branch: master
helm-extra-args: --timeout 600s
chart-dirs:
- charts/incubator
- charts/stable
excluded-charts:
chart-repos:
- bitnami=https://charts.bitnami.com/bitnami
- bjw-s=https://bjw-s.github.io/helm-charts
- jetstack=https://charts.jetstack.io
