{{/* Make sure all variables are set properly */}}
{{- include "bjw-s.common.values.init" . }}

{{/* Append the configMap volume to the volumes */}}
{{- define "adguard-home.configVolume" -}}
enabled: "true"
mountPath: "/tmp/AdGuardHome.yaml"
subPath: "AdGuardHome.yaml"
type: "custom"
volumeSpec:
  configMap:
    name: {{ include "bjw-s.common.lib.chart.names.fullname" . }}-config
{{- end -}}
{{- $_ := set .Values.persistence "adguard-home-config" (include "adguard-home.configVolume" . | fromYaml) -}}

{{/* Render the templates */}}
{{ include "bjw-s.common.loader.generate" . }}