{{- include "bjw-s.common.values.init" . -}}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "bjw-s.common.lib.chart.names.fullname" . }}-config
  labels:
    {{- include "bjw-s.common.labels" . | nindent 4 }}
data:
  AdGuardHome.yaml: |
{{ .Values.config | indent 4 }}