apiVersion: v2
appVersion: 1.0.0
description: ${CHARTNAME} helm package
name: ${CHARTNAME}
version: 1.2.2
kubeVersion: ">=1.16.0-0"
keywords:
  - ${CHARTNAME}
home: https://github.com/egeback/helm-charts/charts/${CHARTNAME}
icon: https://${CHARTNAME}.org/icon
sources:
  - https://github.com/${CHARTNAME}/${CHARTNAME}-docker
maintainers:
  - name: ${CHARTNAME}
    email: ${CHARTNAME}@${CHARTNAME}.com
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
annotations:
  artifacthub.io/changes: |
    - kind: added
      description: Initial version