#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

controllers:
  main:
    containers:
      ${CHARTNAME}:
          # -- image repository
          repository: ${CHARTNAME}/${CHARTNAME}
          # -- image tag
          # @default -- chart.appVersion
          tag:
          # -- image pull policy
          pullPolicy: IfNotPresent

        # -- environment variables. See more environment variables in the [${CHARTNAME} documentation](https://${CHARTNAME}.org/docs).
        # @default -- See below
        env:
          # -- Set the container timezone
          TZ: UTC

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    controller: app
    ports:
      http:
        port: 1880

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"

    hosts:
      -  ## Host address. Helm template can be passed.
        host:
        ## Configure the paths for the host
        paths:
          -  ## Path. Helm template can be passed.
            path: /
            ## Ignored if not kubeVersion >= 1.14-0
            pathType: Prefix
            service:
              ## Overrides the service name reference for this path
              name: main
              ## Overrides the service port reference for this path
              port: portal-https
              identifier: ${CHARTNAME}

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence: {}
  # data:
  #   enabled: false
  #   mountPath: /data