---
apiVersion: v2
appVersion: v0.107.27
description: DNS proxy as ad-blocker for local network
name: adguard-home
version: 1.0.0
kubeVersion: ">=1.16.0-0"
keywords:
  - adguard-home
  - adblock
  - dns
home: https://github.com/k8s-at-home/charts/tree/master/charts/stable/adguard-home
icon: https://avatars3.githubusercontent.com/u/8361145?s=200&v=4?sanitize=true
sources:
  - https://github.com/AdguardTeam/AdGuardHome
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts
    version: 1.3.2
maintainers:
  - name: egeback
    email: marky@egeback.se
annotations:
  artifacthub.io/changes: |-
    - kind: changed
      description: Initial version based on bjw-s common chart 1.3.2