---
apiVersion: v2
appVersion: v0.3.0
description: Cert-manager webhook plugin to support ACME DNS challenges for CPanel DNS zones
name: cert-manager-cpanel-dns-webhook
version: 1.0.18
kubeVersion: ">=1.16.0-0"
icon: https://raw.githubusercontent.com/cert-manager/community/4d35a69437d21b76322157e6284be4cd64e6d2b7/logo/logo-small.png
keywords:
  - cert-manager-webbook
  - dns
  - cpanel
home: https://github.com/egeback/helm-charts/blob/main/charts/cert-manager-cpanel-dns-webhook
sources:
  - https://github.com/jamesorlakin/cert-manager-cpanel-dns-webhook
dependencies:
  - name: cert-manager
    repository: https://charts.jetstack.io
    version: v1.19.3
    condition: cert-manager.enabled
maintainers:
  - name: egeback
    email: marky@egeback.se
annotations:
  artifacthub.io/changes: |2
      - kind: changed
        description: Update image tags or configuration in values.yaml
      - kind: changed
        description: Upgraded `cert-manager` chart dependency to version v1.19.3
