{{- if not .Values.certManager.renderTemplates -}}
apiVersion: v1
kind: Secret
metadata:
  name: '{{include "cert-manager-cpanel-dns-webhook.servingCertificate" .}}'
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: '{{.Chart.AppVersion}}'
    app.kubernetes.io/instance: '{{include "cert-manager-cpanel-dns-webhook.name" .}}'
    helm.sh/chart: '{{include "cert-manager-cpanel-dns-webhook.chart" .}}'
type: kubernetes.io/tls
data:
  tls.crt: |
    MIIDATCCAemgAwIBAgIUJPo1jRIQ01GsJ0EKtE04GJsSZlAwDQYJKoZIhvcNAQEL
    BQAwEDEOMAwGA1UEAwwFZHVtbXkwHhcNMjYwMjExMTY1MzQwWhcNMzYwMjA5MTY1
    MzQwWjAQMQ4wDAYDVQQDDAVkdW1teTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
    AQoCggEBALbQqaFyrr8NAN3UA54Hf48H7EpFpUW19a065kJ6H3asu5VlDlf3vrUV
    Aol1vb2cyMXR4dG+1oNNSzIjC0VrmQiKHNp4xKHjjT5UTurGMgeTNpDMMbE4d+AG
    4yOVF+RvSLW4vEAdv3uu42q5grfaBBCvcJQ4b5uQ1aUVTw2XdNzQjJCDlor/K+aV
    wHLPmyotyKKCkHtIeXujzcvJkKg4S+8cniQA8CBcv3nXhHblzpcDKXHq/v4e3lj6
    ZU6bpHylIAmaxBw5/3rRQk4hhyc/XtRmDziTfIqyV6JOmsCq9KbUov9cYHOoKOoQ
    qJBm0m0EqAddRUpAJ3wB7dpasnGlLXMCAwEAAaNTMFEwHQYDVR0OBBYEFARDWtdN
    82J0oSGVPBmqeXp/9tSKMB8GA1UdIwQYMBaAFARDWtdN82J0oSGVPBmqeXp/9tSK
    MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBAG2xz5Nk37cme82U
    Zq/RUMBQ67fLPOvBPvlG0cjBhNBW/ZHVyvhOia+6Xq7UevEiCnveLbw85brVq4P0
    BcXSr0lO8INouB2PHhQnkfN2i/LaK2DIGUCMhmePb0seMThgFAl8yZH4vDiQXX6L
    74MtgebmXBCK4wRCKXTRBlx8hv448iFYfq5qHQ7kFega+vupOH7sTSe+SixRaj7L
    WglvVgolpsXU9BWmLLcJr74Qrm1PHwZDko9qulqU9816pA/W6BnxazB1dp8DVqOl
    VlXBFlyafNRSGQYTPje7YQVFdNeYGCzUJodyu69/+d9EP9i5Py3iPjpsos9YU4Oj
    o11ku/A=
  tls.key: |
    MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC20Kmhcq6/DQDd
    1AOeB3+PB+xKRaVFtfWtOuZCeh92rLuVZQ5X9761FQKJdb29nMjF0eHRvtaDTUsy
    IwtFa5kIihzaeMSh440+VE7qxjIHkzaQzDGxOHfgBuMjlRfkb0i1uLxAHb97ruNq
    uYK32gQQr3CUOG+bkNWlFU8Nl3Tc0IyQg5aK/yvmlcByz5sqLciigpB7SHl7o83L
    yZCoOEvvHJ4kAPAgXL9514R25c6XAylx6v7+Ht5Y+mVOm6R8pSAJmsQcOf960UJO
    IYcnP17UZg84k3yKsleiTprAqvSm1KL/XGBzqCjqEKiQZtJtBKgHXUVKQCd8Ae3a
    WrJxpS1zAgMBAAECggEAAN/fp9uOFXDg+66rc8KSbCM8EKDjqQE1UyZQeqnt45nw
    7caFeos/WMtobzLmfPU2iqe13lR83zTr8qnzQFpC6aULfUoNmr6latJpbDsVey7L
    mIa5iCD+hc5SoNVyP0/+94uSLvZVd6h/AwAvLWT4FwJX1gWtFv/q3bbL4YNDdljw
    98wAlzpB5aB6jT+ktswHSw/zKvKqdiSThPDrlCmL5T6bl3JuowlybI9Tp7sx2Pc/
    ZSt+JlwqE1CGRLDSSAg5IxSpLxnePE8UH183aFc9YU5TSxNjZwnBhBoZLi0d8E7l
    JnmL/SDhKtUdZV5VEQZejfoSHlRchBtI+bl4QJXpUQKBgQDpg3hkSWd2Cs00txdz
    p5/T4J6yzbGTh8ooHOQ/iDtbhZyXHIW1aaKDDu+bA7OwCJ/YrjtOnT2LfrLRMTcD
    jFVn4sSzvsY2is+qcnKk+gCI2fjdgpngzkUAg3cwffASQBnlveVeMj1d9Snl61cU
    /tOj1f2ySM1l46dBm0sYQOYMIwKBgQDIa2JBLOTGsWwgKp2lUCLo171MaLlE1TKF
    0nd4QPUiZQGXHLF2whdb2cHD1vEi6pWmKkJp3ScxzFDm0pojTc6Pe4SY7fIUvE4A
    A2tJbaKv+DegcGq5MXpci1qnsFFzaBcMKZ91qNKqhz+U7fWpimqFVtV+Q5u2MGba
    yLNY0XsGcQKBgHXmFCYGTb9yqrL/8k5Jhs/SLC443nyPZckk9TUCkn2eEzbUhsnW
    gN/M7bsFfnbVk+cx6O3DRCynFp+6Sn13IDPoccoS+z7UjQ8Q48NaGmT+MMGeTBUN
    8BbXSZlpLIn6ZVjyrNkHYqaKvtHAJeKK2s5wn7uhOFtGOs9MGfkv4zajAoGBAIZx
    mqCz9+fdvvW5ALWTk0d06ZRnL9kf11tz+xadJJPlA/MVmWpb+wVvhw7TkkDk8mxc
    Lt8LLq62K5MbtbB3Elin+CQKgnksdHqH0KGaPSckMFSc9Mq0iSupg6+3lHwBWGyd
    Q03PaTphreI+2qvXoWs++8pOmhbWUzjyp3SuWYPRAoGAWQminxo5yEoIzk4oYrpp
    ZnAMQrlxn3ka81c14SBNTxumM9+SxWMcTYBpXp1/6DbojKjohz3lqWSx/RkvKIAG
    5UwR8CrZFtO4saYC5szj4VPvt4t7kUIzcVUFuoEH5mAGUzWD4aYPZUFTu4R3mHyJ
    jDpO2Xcoov9xsus75m0aD/M=
{{- end -}}
