{{- if not .Values.certManager.renderTemplates -}}
apiVersion: v1
kind: Secret
metadata:
  name: '{{include "cert-manager-cpanel-dns-webhook.servingCertificate" .}}'
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/version: '{{.Chart.AppVersion}}'
    app.kubernetes.io/instance: '{{include "cert-manager-cpanel-dns-webhook.name" .}}'
    helm.sh/chart: '{{include "cert-manager-cpanel-dns-webhook.chart" .}}'
type: kubernetes.io/tls
stringData:
  tls.crt: "dummy"
  tls.key: "dummy"
{{- end -}}
