#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: teslamate/teslamate
  # -- image tag
  # @default -- chart.appVersion
  tag:
  # -- image pull policy
  pullPolicy: IfNotPresent


#
# Additional containers to enhance
#
# additionalContainers:
#   teslamateapi:
#     name: teslamateapi
#     image: tobiasehlert/teslamateapi:1.16.1
#     env:
#       ENCRYPTION_KEY: "{{ .Values.env.ENCRYPTION_KEY }}"
#       DATABASE_USER: "{{ .Values.postgresql.auth.username }}"
#       DATABASE_PASS: "{{ .Values.postgresql.auth.postgresPassword }}"
#       DATABASE_NAME: "{{ .Values.postgresql.auth.database }}"
#       DATABASE_HOST: "{{ .Values.env.DATABASE_HOST }}"
#       MQTT_HOST: "{{ .Values.env.MQTT_HOST }}"
#       TZ: "{{ .Values.env.TZ }}"
#   teslamateagile:
#     image: mattjeanes/teslamateagile:v1.12.0
#     env:
#       DATABASE_USER: "{{ .Values.postgresql.auth.username }}"
#       DATABASE_PASS: "{{ .Values.postgresql.auth.postgresPassword }}"
#       DATABASE_NAME: "{{ .Values.postgresql.auth.database }}"
#       DATABASE_HOST: "{{ .Values.env.DATABASE_HOST }}"
#       TeslaMate__UpdateIntervalSeconds: 300
#       TeslaMate__GeofenceId: 1
#       TeslaMate__EnergyProvider: Tibber
#       Tibber__AccessToken: MyAccessToken
#       TeslaMate__FeePerKilowattHour: 0
#       TZ: "{{ .Values.env.TZ }}"
#   teslamate-abrp:
#     image: fetzu/teslamate-abrp:latest
#     env:
#       MQTT_SERVER: "{{ .Values.env.MQTT_HOST }}"
#       CAR_NUMBER: 2
#       CAR_MODEL: tesla:my:19:bt37:awd
#       USER_TOKEN: 3ec94b70-db8b-4f83-b012-25bcb66f8a1c


# -- environment variables. See [teslamate docs](https://docs.teslamate.org/docs/configuration/environment_variables) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Postgres database hostname
  DATABASE_HOST: '{{ include "bjw-s.common.lib.chart.names.fullname" .}}-postgresql'
  # -- Postgres database user name
  DATABASE_USER: '{{ "Values.postgresql.auth.username" | default "postgres" }}'
  # -- Postgres database password
  DATABASE_PASS: "{{ .Values.postgresql.auth.password }}"
  # -- Postgres database password
  DATABASE_NAME: "{{ .Values.postgresql.auth.database }}"
  # -- Disables the MQTT feature if `true`
  DISABLE_MQTT: "false"
  # -- MQTT server host
  MQTT_HOST: ""
  # -- MQTT server port
  MQTT_PORT: 1883
  # -- Teslamate encryption key
  ENCRYPTION_KEY: "MySuperSecretEncryptionKey"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 4000
  # teslamate-api:
  #   ports:
  #     http2:
  #       port: 8080

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

  #
  # Add ingress for teslamate-api
  # teslamate-api:
  #   enabled: true
  #   hosts:
  #     - host: teslamate-api.example.com
  #       paths:
  #         - path: /
  #           pathType: Prefix
  #           service:
  #             name: teslamate-teslamate-api
  #             port: 8080

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  import:
    enabled: false
    mountPath: /opt/app/import

# -- Enable and configure postgresql database subchart under this key.
#    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
# @default -- See values.yaml
postgresql:
  enabled: false
  auth:
    postgresPassword: teslamate-pass
    password: teslamate-pass
    database: teslamate
    username: teslamate
  primary:
    persistence:
      enabled: false
