#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: teslamate/teslamate
  # -- image tag
  tag: 1.27.2
  # -- image pull policy
  pullPolicy: IfNotPresent


# additionalContainers:
#   teslamateapi:
#     #enabled: false
#     name: teslamateapi
#     image: tobiasehlert/teslamateapi
#     tag: 1.16.0
#     env:
#       - ENCRYPTION_KEY="{{ include .Values.env.ENCRYPTION_KEY }}"
#       - DATABASE_USER='{{ include "Values.postgresql.auth.username" .}}-postgresql'
#       - DATABASE_PASS="{{ include .Values.postgresql.auth.postgresPassword }}"
#       - DATABASE_NAME="{{ include .Values.postgresql.auth.database }}"
#       - DATABASE_HOST='{{ include "common.names.fullname" .}}-postgresql'
#       - MQTT_HOST="{{ include .Values.env.MQTT_HOST }}"
#       - TZ="{{ include .Values.env.TZ }}"


# -- environment variables. See [teslamate docs](https://docs.teslamate.org/docs/configuration/environment_variables) for more details.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Postgres database hostname
  DATABASE_HOST: '{{ include "bjw-s.common.lib.chart.names.fullname" .}}-postgresql'
  # -- Postgres database user name
  DATABASE_USER: '{{ "Values.postgresql.auth.username" | default "postgres" }}'
  # -- Postgres database password
  DATABASE_PASS: "{{ .Values.postgresql.auth.password }}"
  # -- Postgres database password
  DATABASE_NAME: "{{ .Values.postgresql.auth.database }}"
  # -- Disables the MQTT feature if `true`
  DISABLE_MQTT: "false"
  # -- MQTT server host
  MQTT_HOST: ""
  # -- MQTT server port
  MQTT_PORT: 1883
  # -- Teslamate encryption key
  ENCRYPTION_KEY: "MySuperSecretEncryptionKey"

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 4000

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  import:
    enabled: false
    mountPath: /opt/app/import

# -- Enable and configure postgresql database subchart under this key.
#    For more options see [postgresql chart documentation](https://github.com/bitnami/charts/tree/master/bitnami/postgresql)
# @default -- See values.yaml
postgresql:
  enabled: false
  auth:
    postgresPassword: teslamate-pass
    password: teslamate-pass
    database: teslamate
    username: teslamate
  primary:
    persistence:
      enabled: false
 