#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

controllers:
  main:
    containers:
      main:
        # -- environment variables. See more environment variables in the [image documentation](https://github.com/jacobalberty/unifi-docker#environment-variables).
        # @default -- See below
        env:
          # -- Set the container timezone
          TZ: UTC
          # -- Run UniFi as root
          RUNAS_UID0: "false"
          # -- Specify the user ID the application will run as
          UNIFI_UID: "999"
          # -- Specify the group ID the application will run as
          UNIFI_GID: "999"
          # -- Java Virtual Machine (JVM) initial, and minimum, heap size
          # Unset value means there is no lower limit
          JVM_INIT_HEAP_SIZE:
          # -- Java Virtual Machine (JVM) maximum heap size
          # For larger installations a larger value is recommended.
          # For memory constrained system this value can be lowered.
          JVM_MAX_HEAP_SIZE: 1024M
          # # -- External MongoDB URI
          # DB_URI:  # mongodb://unifi-mongodb:27017/unifi
          # STATDB_URI:  # mongodb://unifi-mongodb:27017/unifi_stat
          # DB_NAME:  # unifi
        image:
          # -- image repository
          repository: jacobalberty/unifi
          # @default -- chart.appVersion
          tag: "{{ .Chart.AppVersion }}"
          # -- image pull policy
          pullPolicy: IfNotPresent

# -- pod security context.
# @default -- See below
defaultPodOptions:
  podSecurityContext:
    fsGroup: 999

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    controller: main
    primary: true
    ports:
      http:
        port: 8443
        protocol: HTTPS
  controller:
    controller: main
    enabled: true
    type: NodePort
    ports:
      controller:
        enabled: true
        port: 8080
        protocol: TCP
  portal:
    controller: main
    enabled: false
    ports:
      portal-http:
        port: 8880
        protocol: HTTP
      portal-https:
        port: 8843
        protocol: HTTPS
  speedtest:
    controller: main
    enabled: true
    ports:
      speedtest:
        port: 6789
        protocol: TCP
  stun:
    controller: main
    enabled: true
    type: NodePort
    ports:
      stun:
        port: 3478
        protocol: UDP
  syslog:
    controller: main
    enabled: true
    type: NodePort
    ports:
      syslog:
        port: 5514
        protocol: UDP
  discovery:
    controller: main
    enabled: true
    type: NodePort
    ports:
      discovery:
        port: 10001
        protocol: UDP

# -- Configuration for external MongoDB.
# When enabled, environment variables will be set automatically.
mongodb:
  enabled: false
  # -- Connection URI for the main database
  # @default -- mongodb://mongo/unifi
  dbUri: ""
  # -- Connection URI for the stats database
  # @default -- mongodb://mongo/unifi_stat
  statDbUri: ""
  # -- Database name
  # @default -- unifi
  databaseName: ""
