#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#
controllers:
  main:
    containers:
      app:
        image:
          # -- image repository
          repository: esphome/esphome
          # -- image tag
          # @default -- chart.appVersion
          tag: "{{ .Chart.AppVersion }}"
          # -- image pull policy
          pullPolicy: IfNotPresent

        # -- environment variables. See more environment variables in the [esphome documentation](https://esphome.org).
        # @default -- See below
        env:
          # -- Set the container timezone
          TZ: UTC
          # ESPHOME_DASHBOARD_USE_PING: 'true'

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    controller: main
    ports:
      http:
        port: 6052

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: false
    hosts:
    - host: esphome.example.com
      paths:
        - path: /
          pathType: Prefix
          service:
            identifier: app
            name: app
            port: http

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence: {}
  # config:
  #   enabled: false
  #   mountPath: /data